# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site ä¸ç”¨åŠ å¼•å·
title: â­ï¸é½ä¸‹æ— è´°â­ï¸
subtitle: Weidows ã® Nest
description: May all the beauty be bless.âœ¨
keywords: Weidows Website blog Java, Javadoc, VScode, Maven, å¯¹è±¡, ç¼–ç , è®¾è®¡æ¨¡å¼, JVM, Lambda, PS, å¤‡å¿˜å½•, è®¾è®¡, API, æ‘„å½±, PHP, Website, LaTeX, yaml, SSH, Linux, Markdown, éŸ³ä¹, å“²å­¦, ç”Ÿæ´», å¥èº«, ç¬”è®°, æ¨è, é¢è¯•, IDEA, HTML, CSS, JavaScript, English, æˆé•¿è·¯çº¿, Font, VR, ç½‘è¯¾, Manjaro, è®¡ç®—æœºç³»ç»Ÿ, æœåŠ¡å™¨, è™šæ‹Ÿæœº, æ ‘è“æ´¾, Windows, Docker, å¤šçº¿ç¨‹, è¿›ç¨‹, CPU, Scoop, Git, Python, Node, Ubuntu, wsl2, ç¯å¢ƒå˜é‡, Aria2, å·¥å…·, å›¾åºŠ, çˆ¬è™«, MS, package, Tomcat, MyBatis, Map, CRUD, æ•°æ®åº“, æ³¨è§£, æ—¥å¿—, åˆ†é¡µ, MySQL, JDBC, SQL, å‰ç«¯, JSON, JavaWeb, Servlet, Cookie, Session, JSP, Filter, æ¶æ„, åå°„, Vue, CORS, å¤§å‰ç«¯, JQuery, npm, yarn, C, Cmake, OpenGL, conan, ç†è®ºçŸ¥è¯†, Processing, Anaconda, shell, PowerShell, å®å¡”é¢æ¿, æç¬‘, é«˜èƒ½, å¿«æ·é”®, æµè§ˆå™¨, Hexo, Github, PyCharm, Copilot, æ’ä»¶, Emmet, ç¾åŒ–, snippet, Node.Js, SEO, Pjax, butterfly, pug, styl, ä¼˜åŒ–, é­”æ”¹
author: â›âWeidowsâ â
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: "https://weidows.github.io"
root: "/"
# é»˜è®¤é…ç½®permalink: :year/:month/:day/:title/
permalink: post/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  # - "*.html"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 8
  order_by: -date

# Category & Tag ç”¨æ¥ä¿®æ”¹å¯¹åº”ç›®æ ‡
# æ•°æ®ç»“æ„ä¸ç®—æ³•: algorithm
# Hexo: hexo (è¿™ç§æ— æ•ˆ,è‹±æ–‡çš„è½¬æ¢å°±ä¸ç”¨äº†)
default_category: uncategorized
category_map:

tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

live2d:
  enable: true
  scriptFrom: jsdelivr
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-tororo # ç”¨åˆ°çš„æ¨¡å‹æ–‡ä»¶å¤¹åç§°
  display:
    position: left
    width: 180
    height: 300
  mobile:
    show: false
  react:
    opacity: 0.7

bangumi:
  enable: true
  path: tags/bangumis.html
  vmid: 38283369 # å“”å“©å“”å“©ç•ªå‰§é¡µé¢çš„ vmid(uid)
  title: "ç•ª ã® è¡¨" # é¡µé¢çš„æ ‡é¢˜
  quote: <h1 align="center">çœ‹çœ‹åˆæ–°å¨¶æ¥å‡ ä¸ªè€å©†âŠ™âˆ€âŠ™ï¼</h1> # å†™åœ¨é¡µé¢å¼€å¤´çš„ä¸€æ®µè¯ï¼Œæ”¯æŒ html è¯­æ³•
  show: 1 # åˆå§‹æ˜¾ç¤ºé¡µé¢ï¼š0: æƒ³çœ‹ , 1: åœ¨çœ‹ , 2: çœ‹è¿‡ï¼Œé»˜è®¤ä¸º 1
  loading: "https://cdn.jsdelivr.net/gh/Weidows/Images/img/loading.webp" # å›¾ç‰‡åŠ è½½å®Œæˆå‰çš„ loading å›¾ç‰‡

sitemap:
  path: sitemap.xml
  tag: false
  category: false

steam:
  enable: true
  steamId: "76561198321099712" # steam Id(éœ€è¦æ”¾åœ¨å¼•å·é‡Œ),å°†steamåº“è®¾ç½®ä¸ºå…¬å¼€
  path: tags/games.html # é¡µé¢è·¯å¾„ï¼Œé»˜è®¤steamgames/index.html
  title: â­ï¸å…»Gåœºâ­ï¸
  quote: Steamç»™çˆ·çˆ¬!åˆ«è®©æˆ‘å®¶EPICè¯¯ä¼š( # å†™åœ¨é¡µé¢å¼€å¤´çš„ä¸€æ®µè¯
  tab: all # allæˆ–recent, all: æ‰€æœ‰æ¸¸æˆ, recent: æœ€è¿‘æ¸¸ç©çš„æ¸¸æˆ
  length: 1000
  imgUrl: https://47i7-my.sharepoint.com/personal/utsuko27_bilibili_hk_cn/Documents/Pictures/bed/gallery/Game/DOAX-VenusVacation/%E6%A8%AA%E5%B1%8F/9f84a622d3519deb534a9da403e0e50b8daba6e9b5aeff0edb87ac8a880b616f.jpeg # å›¾ç‰‡é“¾æ¥ï¼Œåœ¨quoteä¸‹é¢æ”¾ä¸€å¼ å›¾ç‰‡ï¼Œå›¾ç‰‡é“¾æ¥åˆ°Steamä¸ªäººèµ„æ–™ï¼Œå¯ç•™ç©º
  # å¦‚æœæ— æ³•è®¿é—®steamç¤¾åŒºçš„è¯è¯·ä½¿ç”¨ä»£ç†
  proxy:
    # host: localhost # ä»£ç†ipæˆ–åŸŸå
    # port: 7890 # ä»£ç†ç«¯å£

# åšæ–‡å‹ç¼© - hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:
    - "**/*.mmd/*"
neat_css:
  enable: true
  exclude:
    - "**/*.min.css"
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "**/*.min.js"
    - "**/jquery.fancybox.pack.js"
    - "**/index.js"

deploy:
  # - type: git
  #   repo:
  #     - https://gitee.com/Weidows/Weidows.git
  #     - https://github.com/Weidows/Weidows.github.io.git
  #   branch: main
  # ä¸èƒ½å†™æˆä»¥ä¸Šé‚£æ ·,gitä¼šæäº¤å‡ºé”™!
  - type: git
    repo: git@github.com:Weidows/Weidows.github.io.git
    branch: main
  # - type: baidu_url_submitter
  - type: cjh_google_url_submitter
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter

hexo_submit_urls_to_search_engine:
  submit_condition: count # Submitted condition, optional value: count | period, Now only supports count
  count: 100 # Submit the latest 10 links
  period: 900 # Submit a link with a modification time of 900 seconds
  google: 0 #  Whether to submit to Google, optional values: 1 | 0 (0: No; 1: Yes)
  bing: 1 #  Whether to submit to bing, optional value: 1 | 0 (0: no; 1: yes)
  baidu: 1 # Whether to submit to baidu, optional value: 1 | 0 (0: no; 1: yes)
  txt_path: submit_urls.txt ## The address of the text document, the link to be pushed will be saved in this text document
  baidu_host: https://weidows.github.io ## Domain name registered in Baidu webmaster platform
  baidu_token: tXk4TVcpo7pxHIuK ## Please note that this is your secret key, so do not publish the website source code in the public repository!
  bing_host: https://weidows.github.io ## Domain name registered in Bing webmaster platform
  bing_token: 603e84bf2d784f19bbbda4a04b706e81 ## Please note that this is your secret key, so do not publish the website source code in the public repository!
  google_host: https://weidows.github.io ## Domain name registered in Google webmaster platform
  google_key_file: Project.json #Store the json file of the google key in the root directory of the website (same location as the hexo _config.yml file), please do not publish the source code of the website in the public warehouse!
  replace: 0 # Whether to replace some substrings in links, optional value: 1 | 0 (0: no; 1: yes)
  find_what:
  replace_with:

# Ice Kano Plus_in
# Hexo Github Canlendar
# Author: Ice Kano
# Modify: Leteä¹ç‰¹
# butterfly
githubcalendar:
  enable: true
  priority: 3
  enable_page: /
  user: Weidows
  layout:
    type: id
    name: recent-posts
    index: 0
  githubcalendar_html: '<div class="recent-post-item" style="width:100%;height:auto;padding:10px;"><div id="github_loading" style="width:10%;height:100%;margin:0 auto;display: block"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 50 50" style="enable-background:new 0 0 50 50" xml:space="preserve"><path fill="#d0d0d0" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z" transform="rotate(275.098 25 25)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.6s" repeatCount="indefinite"></animateTransform></path></svg></div><div id="github_container"></div></div>'
  pc_minheight: 280px
  mobile_minheight: 0px
  color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']"
  api: https://python-github-calendar-api.vercel.app/api
  # api: https://python-gitee-calendar-api.vercel.app/api
  calendar_js: https://cdn.jsdelivr.net/gh/Zfour/hexo-github-calendar@1.21/hexo_githubcalendar.js
  plus_style: ""

# ç»Ÿè®¡å›¾è¡¨ï¼Œæ”¯æŒå‘å¸ƒæ–‡ç« ç»Ÿè®¡ã€å‘å¸ƒæ—¥å†ã€Topæ ‡ç­¾ç»Ÿè®¡ã€åˆ†ç±»ç»Ÿè®¡ã€åˆ†ç±»é›·è¾¾ã€‚
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # æ˜¯å¦å¯ç”¨åŠŸèƒ½
  postsChart:
    title: ğŸ‰æ–‡ç« å‘å¸ƒç»Ÿè®¡ # è®¾ç½®æ–‡ç« å‘å¸ƒç»Ÿè®¡çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
    interval: 1 # æ¨ªåæ ‡é—´éš”
  tagsChart:
    title: ğŸ‰æ ‡ç­¾ç»Ÿè®¡ # è®¾ç½®æ ‡ç­¾ç»Ÿè®¡çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
    interval: 0 # æ¨ªåæ ‡é—´éš”
  postsCalendar_Title: #æ–‡ç« å‘å¸ƒæ—¥å† # è®¾ç½®å‘å¸ƒæ—¥å†çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
  categoriesChart_Title: # è®¾ç½®åˆ†ç±»ç»Ÿè®¡çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º
  categoriesRadar_Title: # è®¾ç½®åˆ†ç±»é›·è¾¾çš„æ ‡é¢˜ï¼Œé»˜è®¤ä¸ºç©º

# opitions for renderer
markdown:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      options:
        strict: false

auto_dir_categorize:
  enable: true # options:true, false; default is true
  force: true # options:true, false; default is false

# https://github.com/dailyrandomphoto/hexo-easy-tags-plugin
# enable (default: true) - enable this plugin, or disable it.
# tag_name_case (default: 0) - option to transform all tags name to lowercase of uppercase. 0 no transform, 1 lowercase, 2 uppercase.
# sort_ignore_case (default: true) - if set to false, the order of the tags is case sensitive. Affects list_tags(), tagcloud() helpers.
# action (default: correct) - if set to report, print conflicted tags and exit.
easy_tags_plugin:
  enable: true
  tag_name_case: 1
  sort_ignore_case: true

  # Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-butterfly
