name: Build and Deploy

on: [push] # è§¦å‘æ¡ä»¶(git æŽ¨é€æ—¶)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2 # ä¸‹é¢è¿™ä¸ªæœ€å¥½è®¾æˆ false
        with:
          persist-credentials: false

      - name: My-Tasks
        run: |
          # è¿žé€šssh
          mkdir ~/.ssh
          cp ./.github/config ~/.ssh/config
          echo "${{ secrets.RSA }}" > ~/.ssh/Github_rsa
          chmod 600 ~/.ssh/*
          # ssh -T git@github.com

          # è®¾ç½®Git
          git config --global user.name "Weidows"
          git config --global user.email "utsuko27@qq.com"

      - name: Install and Build ðŸ”§
        run: |
          npm install
          npm run build
          npm run deploy
        env:
          CI: true
