name: Build and Deploy

on: [push] # è§¦å‘æ¡ä»¶(git æ¨é€æ—¶)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: My-Tasks
        run: |
          # è¿é€šssh
          mkdir ~/.ssh
          cp ./.github/config ~/.ssh/config
          echo "${{ secrets.RSA }}" > ~/.ssh/Github_rsa
          chmod 600 ~/.ssh/*
          # ssh -T git@github.com

          # è®¾ç½®Git
          git config --global user.name "Weidows"
          git config --global user.email "utsuko27@qq.com"

      - name: Install and Build ğŸ”§
        run: |
          # npm cache clean --force
          # rm -rf node_modules

          # å‡çº§ npm
          npm install -g npm

          # è§£å†³ä¾èµ–å†²çª
          # npm install --legacy-peer-deps
          npm ci

          npm run get-bilibili-steam
          npm run ä¸€é”®ä¸‰è¿
